### ISSUE TITLE
`retry: false` not respected when forwarding

### ISSUE THREAD

**Issue by fregante** [pixiebrix/webext-messenger#211]
This isn't used in the app at the moment, but the demo extension's tests are failing on:

- https://fregante.github.io/pixiebrix-testing-ground/Will-call-other-CS-via-background

The method works correctly when called directly from the background.

**Comment by fregante** [comment]
Seen on https://fregante.github.io/pixiebrix-testing-ground/Will-call-other-CS-via-background

```
# does not retry if specifically asked not to
ok 12 should be strictly equal
api.test.js:12077 {actualDuration: 4326.699999928474, expectedDuration: 0, maximumDuration: undefined}
not ok 13 It should take about 0s (took 4.326699999928475s)
  ---
    operator: ok
    expected: true
    actual:   false
    stack: |-
      Error: It should take about 0s (took 4.326699999928475s)
          at Test.assert [as _assert] (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:7029:78)
          at Test.assert (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:7123:10)
          at expectDuration (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:12083:12)
          at Test.<anonymous> (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:330:39)
  ...

# retries until it times out even if webext-messenger was loaded (but nothing was registered)
ok 14 should be strictly equal
{actualDuration: 105.29999995231628, expectedDuration: 4000, maximumDuration: 5000}
not ok 15 It should take between 4 and 5 seconds (took 0.10529999995231629s)
  ---
    operator: ok
    expected: true
    actual:   false
    stack: |-
      Error: It should take between 4 and 5 seconds (took 0.10529999995231629s)
          at Test.assert [as _assert] (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:7029:78)
          at Test.assert (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:7123:10)
          at expectDuration (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:12082:28)
          at Test.<anonymous> (chrome-extension://booopmeknilocdklkhphgckpcolonbgi/contentscript/api.test.js:340:39)
  ...
  ```
